### PR TITLE
fix: Chart version must be immutable

### PR DESCRIPTION
**Pull request by abdennour**
This is to patch the chart version according to changes of https://github.com/presslabs/mysql-operator/pull/570

closes/fixes #570

---
 - [x] I've made sure the [Changelog.md](https://github.com/presslabs/mysql-operator/blob/master/Changelog.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by AMecea** [comment]
Hi @abdennour, don't forget to rebase in order to merge this. Thanks!

**Comment by abdennour** [comment]
@AMecea  your request is not clear. please explain more.

**Comment by AMecea** [comment]
This branch is in conflict with some changes in the `master` branch, so you have to fix those conflicts by [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

image

**Comment by AMecea** [comment]
The chart version was bumped in #593. I will close this. Thank you for your contribution!

**Pull request closed without merging**
