### PR TITLE
Make user-defined InitContainers take the precedence

### LINKED ISSUE #599: User-defined InitContainers should take the precedence
For those `securityContext.fsGroup` not working case.

user-defined InitContainers should run before `init` and any other existing init containers.

Then user-defined InitContainers can run `chown -R 999:999 /var/lib/mysql` to change the permission.

Probably need to modify code [here](https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/mysqlcluster/internal/syncer/statefullset.go#L346)

### PR DESCRIPTION
**Pull request by bananaappletw**
closes/fixes #599 

---
 - [X] I've made sure the [Changelog.md](https://github.com/presslabs/mysql-operator/blob/master/Changelog.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by AMecea** [comment]
Hi @bananaappletw, thank you for your contribution! This looks good!

Please rebase from master.

**Comment by bananaappletw** [comment]
@AMecea 
ok

**Comment by AMecea** [comment]
Sorry, this requires a new rebase. :smile: This is due to the `Changelog.md` file.

**Comment by bananaappletw** [comment]
@AMecea ok

**Comment by bananaappletw** [comment]
@AMecea Could you review this pull request?

**Pull request merged**
